spring.application.name=vuln-dashboard
# Use Docker Postgres by default
spring.datasource.url=jdbc:postgresql://localhost:5432/VulScanDb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=vulscan
spring.datasource.password=vulscan
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false
# disable H2 console when using Postgres
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2

